### ISSUE TITLE
STA MODE 

### ISSUE THREAD

**Issue by jpfree** [DroneBridge/ESP32#13]
hello ,i wan it connetc to a  4g dongle for remote ,but now it's in ap mode ,how can i change it to STA MODE or sta+ap?

and can you release the latest Compiled version if you have time ,thanks

**Comment by seeul8er** [comment]
To set it to STA mode you need to manually change the source code to do so. [You have to change stuff here](https://github.com/DroneBridge/ESP32/blob/master/main/main.c#L93) to get it done. The ESP Docs will tell you how to enable STA mode.

I see what I can do for an updated release.

**Comment by jpfree** [comment]
> 

hello bigman,can you release a sta mode version if you free time?thanks very much
