### ISSUE TITLE
Currently unable to handle this request 

### ISSUE THREAD

**Issue by theonlyakhil** [DroneBridge/ESP32#16]
![Screenshot (35)](https://user-images.githubusercontent.com/25252405/122458581-9893cb00-cfcd-11eb-985c-cc3ce4f3e939.png)
i am getting a page like this after saving all the setting

**Comment by GeorgeFlorian** [comment]
Try using Mozila Firefox instead of Chrome. It worked for me.

**Comment by seeul8er** [comment]
Fixed in release v1.0 - #21
