### ISSUE TITLE
QGC stuck at "Reading params"

### ISSUE THREAD

**Issue by GeorgeFlorian** [DroneBridge/ESP32#19]
After weeks of trying to make this work I still can't get any parameters from the drone.

I have tried TCP and the QGC gets stuck at reading parameters.
I have tried UDP and the QGC gets stuck at reading parameters.

If and when I can connect to the softAP and establish a connection (TCP or UDP) with the ESP I get nothing from the drone.

These are the Drone settings:
![settings](https://user-images.githubusercontent.com/39895513/124924933-9f2dc500-e004-11eb-938a-ed6c6abcc826.png)

I've tried both MavLink v1 and v2

The drone ports is on 3v3.
![3v3](https://user-images.githubusercontent.com/39895513/124925225-e61bba80-e004-11eb-9cf3-ec99fe0bc7f6.png)

Nothing works.

**Comment by GeorgeFlorian** [comment]
@seeul8er Any thoughts on this ?

**Comment by seeul8er** [comment]
The code is pretty old now - seems like the recent release broke some stuff. I really do not have much time at hand. I guess the HTTP Server part needs a complete rewrite to finally fix things. I think it is also a good idea to remove parts of the UDP server. That should make it simpler and more robust.
I see what I can come up with till the end of this week.

**Comment by seeul8er** [comment]
Fixed in release v1.0 - #21
