### ISSUE TITLE
Installed version 0.6 but no SSID is visible

### ISSUE THREAD

**Issue by sujiv0** [DroneBridge/ESP32#20]
I installed v0.6, no SSID is visible to connect. With v0.5 DroneBridge SSID is showing.
Any help.

Thanks,

Sujiv0

**Comment by seeul8er** [comment]
The code is pretty old now - seems like the recent release broke some stuff. I really do not have much time at hand but I'll see if I can get a fix released till end of this week

**Comment by seeul8er** [comment]
Issue is fixed in 07_dev branch. Branch is still under development

**Comment by sujiv0** [comment]
@seeul8er Hi thanks for checking the issue

Sujiv0

**Comment by seeul8er** [comment]
Fixed in release v1.0 - #21
