### ISSUE TITLE
Any plan for supporting ESP32-C3 / ESP32-S2 ?

### ISSUE THREAD

**Issue by Linjieqiang** [DroneBridge/ESP32#26]

**Comment by seeul8er** [comment]
They have less RAM than the "legacy" ESP32. We are already running low on it. My guess RepPanel will not run properly (if at all)

**Comment by seeul8er** [comment]
Sorry. Mixed something up :) No not at the moment. But my guess is that you can just recompile most, if not all of the code for the other ESPs. Might need to adjust some settings because the flash size might be different but not a whole lot I guess.
