### ISSUE TITLE
Not working with APM2.8

### ISSUE THREAD

**Issue by sir-argupta** [DroneBridge/ESP32#33]
Hey
I tried it with apm2.8 it and its not connecting to Mission planner. Any help on this please.

**Comment by seeul8er** [comment]
It is a transparent link that does not care about the protocol etc., so there must be a configuration error on your side.
You will need to provide more information if you want me to help you.
Does the WiFi show up?
Does the Web interface show data?
What's your configuration?
Is there an error message?

**Comment by sir-argupta** [comment]
Does the WiFi show up? - Yes
Does the Web interface show data? - Yes
What's your configuration?

![image](https://user-images.githubusercontent.com/21137415/179349880-dde0b1cd-fa64-4b5d-b764-84ef884fa883.png)


Is there an error message?

![image](https://user-images.githubusercontent.com/21137415/179349912-bc585023-4ea5-4a20-b38f-5981ad7db20c.png)

**Comment by sir-argupta** [comment]
I was using with APM 2.8

**Comment by seeul8er** [comment]
Very strange indeed. Could you try connecting via TCP please.
Does the baud rate of DroneBridge for ESP32 match the baud rate of your flight controller. You have set 115200 in DroneBridge, you will need to set that in the fc as well

**Comment by seeul8er** [comment]
What ESP32 board are you using?

**Comment by sir-argupta** [comment]
I tried both UDP & TCP but it didn't worked.. I'm using ESP WROOM32 board.

**Comment by sir-argupta** [comment]
> Very strange indeed. Could you try connecting via TCP please. Does the baud rate of DroneBridge for ESP32 match the baud rate of your flight controller. You have set 115200 in DroneBridge, you will need to set that in the fc as well

Yes If you see in screenshot that I've attached..

**Comment by sir-argupta** [comment]
Tho Esp8266 worked for me but I want to use esp32 as it'll provide better speed & less lagging of data.

**Comment by seeul8er** [comment]
I am not familiar with AMP l, but are you sure the screenshot shows the baud that the fc has configured on its telemetry output? It is usually set via a parameter.

**Comment by sir-argupta** [comment]
Yes I'm pretty sure for baud rate.
