### ISSUE TITLE
ESP32 LoRa Mode WIFI_PROTOCOL_LR

### ISSUE THREAD

**Issue by Mkorho** [DroneBridge/ESP32#35]
Is it possible to use WIFI_PROTOCOL_LR (LoRa) instead of WIFI_PROTOCOL_11B as the WIFI protocol to gain more range?
https://github.com/DroneBridge/ESP32/blob/c1fcc3f9e42e02903b331857f9179032f29d6198/main/main.c#L168

**Comment by seeul8er** [comment]
According to the docs: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/wifi.html#long-range-lr
You will need an ESP device on the receiving side as well. Other then that I think it should work by just changing that single line of code

**Comment by seeul8er** [comment]
Yes that would be an option. I do not have time at the moment to implement the change
