### ISSUE TITLE
GPIO Sleep Mode ext0/ext1

### ISSUE THREAD

**Issue by Luix333** [DroneBridge/ESP32#37]
This would be more of a feature request. Thanks you in advance for all the people working on this project.

I'm worried about the power consumption of the ESP32. I would like for there to be a way to sleep/wake up (ext0) the ESP32 using a GPIO on Ardupilot. Would this be possible?

**Comment by seeul8er** [comment]
Power consumption is very low compared to other drone subsystems. Not worth the effort for now
