### ISSUE TITLE
ESP32 Rebooting...

### ISSUE THREAD

**Issue by Luviewer** [DroneBridge/ESP32#38]
I downloaded the DroneBridge firmware from Ubuntu20 using espidf. After downloading, esp32 kept restarting. The serial port output is as follows. Thanks!
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7288
load:0x40078000,len:15052
ho 0 tail 12 room 4
load:0x40080400,len:3688
entry 0x4008067c
[0;32mI (29) boot: ESP-IDF v4.3.4-315-gaa8a00c4f0 2nd stage bootloader[0m
[0;32mI (29) boot: compile time 15:40:43[0m
[0;32mI (29) boot: chip revision: 1[0m
[0;32mI (33) boot_comm: chip revision: 1, min. bootloader chip revision: 0[0m
[0;32mI (40) boot.esp32: SPI Speed      : 40MHz[0m
[0;32mI (45) boot.esp32: SPI Mode       : DIO[0m
[0;32mI (49) boot.esp32: SPI Flash Size : 16MB[0m
[0;32mI (54) boot: Enabling RNG early entropy source...[0m
[0;32mI (59) boot: Partition Table:[0m
[0;32mI (63) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (70) boot:  0 nvs              WiFi data        01 02 00009000 00006000[0m
[0;32mI (78) boot:  1 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (85) boot:  2 factory          factory app      00 00 00010000 00100000[0m
[0;32mI (93) boot:  3 www              Unknown data     01 82 00110000 00200000[0m
[0;32mI (100) boot: End of partition table[0m
[0;32mI (104) boot_comm: chip revision: 1, min. application chip revision: 0[0m
[0;32mI (112) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=196a0h (104096) map[0m
[0;32mI (158) esp_image: segment 1: paddr=000296c8 vaddr=3ffb0000 size=03f74h ( 16244) load[0m
[0;32mI (164) esp_image: segment 2: paddr=0002d644 vaddr=40080000 size=029d4h ( 10708) load[0m
[0;32mI (169) esp_image: segment 3: paddr=00030020 vaddr=400d0020 size=8a8b0h (567472) map[0m
[0;32mI (377) esp_image: segment 4: paddr=000ba8d8 vaddr=400829d4 size=13184h ( 78212) load[0m
[0;32mI (420) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (421) boot: Disabling RNG early entropy source...[0m
[0;32mI (432) cpu_start: Pro cpu up.[0m
[0;32mI (432) cpu_start: Starting app cpu, entry point is 0x40081364[0m
[0;32mI (418) cpu_start: App cpu up.[0m
[0;32mI (449) cpu_start: Pro cpu start user code[0m
[0;32mI (449) cpu_start: cpu freq: 160000000[0m
[0;32mI (449) cpu_start: Application information:[0m
[0;32mI (453) cpu_start: Project name:     db_esp32[0m
[0;32mI (458) cpu_start: App version:      v1.0[0m
[0;32mI (463) cpu_start: Compile time:     Jan 11 2023 15:43:49[0m
[0;32mI (469) cpu_start: ELF file SHA256:  e3bc86bc613428de...[0m
[0;32mI (475) cpu_start: ESP-IDF:          v4.3.4-315-gaa8a00c4f0[0m
[0;32mI (482) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (489) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[0;32mI (495) heap_init: At 3FFBA390 len 00025C70 (151 KiB): DRAM[0m
[0;32mI (501) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM[0m
[0;32mI (507) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (514) heap_init: At 40095B58 len 0000A4A8 (41 KiB): IRAM[0m
[0;32mI (521) spi_flash: detected chip: generic[0m
[0;32mI (525) spi_flash: flash io: dio[0m
[0;32mI (530) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
[0;32mI (601) DB_ESP32: Reading settings from NVS[0m
I (621) wifi:wifi driver task: 3ffc3908, prio:23, stack:6656, core=0
[0;32mI (621) system_api: Base MAC address is not set[0m
[0;32mI (621) system_api: read default base MAC address from EFUSE[0m
I (631) wifi:wifi firmware version: aa6486c
I (631) wifi:wifi certification version: v7.0
I (631) wifi:config NVS flash: enabled
I (631) wifi:config nano formating: disabled
I (641) wifi:Init data frame dynamic rx buffer num: 32
I (641) wifi:Init management frame dynamic rx buffer num: 32
I (651) wifi:Init management short buffer num: 32
I (651) wifi:Init dynamic tx buffer num: 64
I (661) wifi:Init static rx buffer size: 1600
I (661) wifi:Init static rx buffer num: 10
I (661) wifi:Init dynamic rx buffer num: 32
[0;32mI (671) wifi_init: rx ba win: 6[0m
[0;32mI (671) wifi_init: tcpip mbox: 32[0m
[0;32mI (681) wifi_init: udp mbox: 6[0m
[0;32mI (681) wifi_init: tcp mbox: 6[0m
[0;32mI (681) wifi_init: tcp tx win: 5744[0m
[0;32mI (691) wifi_init: tcp rx win: 5744[0m
[0;32mI (691) wifi_init: tcp mss: 1440[0m
[0;32mI (701) wifi_init: WiFi IRAM OP enabled[0m
[0;32mI (701) wifi_init: WiFi RX IRAM OP enabled[0m
I (711) wifi:invalid country code string cc=XX

ESP_ERROR_CHECK failed: esp_err_t 0x102 (ESP_ERR_INVALID_ARG) at 0x400873a4
file: "../main/main.c" line 165
func: init_wifi
expression: esp_wifi_set_country(&wifi_country)

abort() was called at PC 0x400873a7 on core 0

Backtrace:0x400817fe:0x3ffbce10 0x400898d5:0x3ffbce30 0x4008fffa:0x3ffbce50 0x400873a7:0x3ffbcec0 0x400d9038:0x3ffbcee0 0x400d956b:0x3ffbd080 0x4015a623:0x3ffbd0a0

ELF file SHA256: e3bc86bc613428de

**Comment by seeul8er** [comment]
Fixed with release v1.2 - updated country code and esp-idf version to 4.4.6
