### ISSUE TITLE
Can the baud rate be higher?

### ISSUE THREAD

**Issue by marseric** [DroneBridge/ESP32#4]
I really like this project. 
I bought some modules to do the experiment. It Works！
But my data is very large and I need a higher baud rate.（1Mbps or higher will be great）
Thank you for this good project, I will always pay attention to it.

**Comment by seeul8er** [comment]
The ESP32 can do more. I guess you are not pushing telemetry, but I'll try to add some more options in the next release.

**Comment by seeul8er** [comment]
Fixed, thanks to @AaronLi
