### ISSUE TITLE
Not working for Adafruit Feather V2

### ISSUE THREAD

**Issue by evaesteban** [DroneBridge/ESP32#40]
Hi,

I'm trying to get this to work with the Adafruit Feather V2 board (https://www.adafruit.com/product/5438) and, even though the esptool process is successful, the AP never gets generated. Have you tested it with this new board?

**Comment by seeul8er** [comment]
Check out the releases: https://github.com/DroneBridge/ESP32/releases/tag/v1.0
You may need to adjust the default UART pins because they may be connected to the flash chip on your board.
