### ISSUE TITLE
WiFi  not showing

### ISSUE THREAD

**Issue by EternAlmox** [DroneBridge/ESP32#44]
Hello,

I build the code and flashed to the ESP32 but WiFi is not showing up. weird thing is my db_esp32.bin file is 763 KB but the one you provide is 792KB am i doing sth wrong ?

**Comment by seeul8er** [comment]
The difference in build size may be due to a different esp-idf version or config. I would not worry too much about it.
Without a logs no one will ever be able to help you. Check `idf-py monitor`
