### ISSUE TITLE
MavFTP does not work

### ISSUE THREAD

**Issue by Target0815** [DroneBridge/ESP32#48]
Hi,

with the current firmware no parameter download with MavFTP works yet. But this has been standard for some time and should therefore work.

**Comment by seeul8er** [comment]
Please check the new v1.5 release. I did fix some UART-related issues. Maybe it is fixed now. Otherwise I will implement some more specific fixes

**Comment by 4O6FPV** [comment]
no issues with mavftp on the latest version with all the 7 I have tested. I would say you can mark this as closed. Picture below is downloading a lua script via mavftp. 
![Screenshot 2024-03-19 183231](https://github.com/DroneBridge/ESP32/assets/22821839/aa4693e4-c986-4e24-b2d0-3741790d98f1)
