### ISSUE TITLE
ESP32 ESP32 LR mode

### ISSUE THREAD

**Issue by kasperg3** [DroneBridge/ESP32#50]
Has the ESP32 Long range mode been evaluated/tested? Or else I might experiment with a long range/low data option.

The ESP32 doc states that ranges up to 1km can be reached by using their patented protocol. 

LR documentation: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/wifi.html#long-range-lr

**Comment by seeul8er** [comment]
No, it hasn't, it requires an ESP as a receiver and a transmitter. Integrating it is very much possible, but I haven't found the time yet.

**Comment by seeul8er** [comment]
Support was added with the latest commit. Function is to be tested and will be part of the new release once it works

**Comment by seeul8er** [comment]
Check the latest Release Candidate for LR support: [https://github.com/DroneBridge/ESP32/releases/tag/v2.0RC1](https://github.com/DroneBridge/ESP32/releases/tag/v2.0RC1)
