### ISSUE TITLE
QGC error binding UDP port: The address is protected

### ISSUE THREAD

**Issue by Aaliyan00** [DroneBridge/ESP32#51]
![qgc](https://github.com/DroneBridge/ESP32/assets/56350506/30bf3dd5-21f3-428d-bdc1-f5e41cac7054)
![dronebridge](https://github.com/DroneBridge/ESP32/assets/56350506/157213e9-3693-4790-8e1b-76425cff6c47)
I am using ESP-WROOM-32 connected to serial 1 of my flight controller. The baud rate is set at 115200 in config as well as dronebridge. I tried with DroneBridgeESP32_v1_2_alt_UART_conf as well as DroneBridgeESP32_v1_2 but i still getting the same error.

**Comment by seeul8er** [comment]
Not an issue of DroenBridge. Seems like something is already bound to the UDP port. Maybe a different GCS or connection.
