### ISSUE TITLE
Resources needed by index.html randomly fail to load with ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by george-hawkins** [DroneBridge/ESP32#53]
I installed the 1.2 release on an ESP32 development board (the classic ESP32, not an S2 or S3) and several of the resources needed by `index.html` always fail to load.

Which ones fail to load seems to be fairly random, sometimes it's the `.css` files or the logo but other times it's the JavaScript files and the UI (unsurprisingly) fails to function.

If I open the developer tools, I can see the failures fairly clearly:
![failures](https://raw.githubusercontent.com/george-hawkins/mjx-donkey-car/master/images/dronebridge-download-failures.png)

As noted, which files fail to load seems random but they always fail with `ERR_CONNECTION_RESET`. I'm using Google Chrome running on a Mac. I can imagine Chrome is fairly aggressive about downloading the files that it sees are needed by `index.html` and it simply overwhelms the ESP32 and it gives up with connection resets.

The solution was to inline everything into the `index.html`, i.e. copy the contents of the `.js` files into the `.html` file and surround them with `<script>` tags and the same for the `.css` files (with `<style>` tags) and replacing the logo file with a data URI (as shown in this [commit](https://github.com/george-hawkins/dronebridge-esp32/commit/6c9fd63c38f43f2b398b64df2047a48008dab073)).

Obviously, a much nicer solution would be to keep the files as they are and do this inlining using some kind of tool so that the result is used in the build process but isn't checked into git.

I described my experiences and how I resolved things in more detail [here](https://github.com/george-hawkins/mjx-donkey-car/blob/master/drone-bridge-esp32.md).

**Comment by seeul8er** [comment]
Thank you for your investigation and hint on that issue. Your idea of fixing it was partially implemented with the new v1.3 release!
