### ISSUE TITLE
Compile with ESP-IDF v5+

### ISSUE THREAD

**Issue by seankovacs** [DroneBridge/ESP32#54]
How are you getting master to compile with v5.1? A lot of changes that break some of the code for me.

**Comment by seeul8er** [comment]
Must be something wrong with your setup then. [Github Action also runs fine](https://github.com/DroneBridge/ESP32/actions/runs/7376670752/job/20069727551).

**Comment by seankovacs** [comment]
I guess so. It's just weird that things like mdns still compile even though it's been [removed](https://esp32.com/viewtopic.php?t=31770) from v5.0 of esp-idf and move into its own component.

**Comment by seankovacs** [comment]
Okay - I see that part in master now...I guess my local was outdated. 🤷

**Comment by seankovacs** [comment]
Should be good here
