### ISSUE TITLE
Module & module interconnection instead of module&phone?

### ISSUE THREAD

**Issue by marseric** [DroneBridge/ESP32#6]
My ground station needs a serial port connection. Is there any way to implement the ESP32 module communication on the ground? This flexibility is better, thank you!

**Comment by seeul8er** [comment]
Not planned for now. You can modify the `config.h` file [of this project](https://github.com/AlphaLima/ESP32-Serial-Bridge) to connect to the DroneBridge for ESP32. You need to set it to `define MODE_STA` instead of MODE_AP. Change the IP & Port according to DB for ESP32 as well
