### ISSUE TITLE
"No such file or directory : 'bootloader.bin'"  error

### ISSUE THREAD

**Issue by Nosgnod5754** [DroneBridge/ESP32#65]
Hello there, 
I'm having trouble flashing dronebridge onto an Adafruit HUZZAH32 - ESP32 Feather. Every time I attempt a flash, I get this message. What does this mean? How do I fix this? I'm very new to this.

![Screenshot 2024-02-28 202537](https://github.com/DroneBridge/ESP32/assets/156618497/21702dd2-0cd1-49bb-b371-97723e50aee5)

**Comment by seeul8er** [comment]
Obviously he can not find the file bootloader.bin. Your current folder esp-idf-v5.1.2-2 is not containing it. Copy the files there and flash again
