### ISSUE TITLE
The flight control board with the ESP32-C3 cannot connect to QGroundControl properly

### ISSUE THREAD

**Issue by YangChen1234** [DroneBridge/ESP32#66]
I don't know how much to fill in the UART TX Pin and UART RX Ping on the DroneBridge page，I tried UART TX Pin = 3, UART RX Pin = 2 according to the schematic, but this did not connect to the ground station
![cc7ebf06f1c81bcc46ce4abe0b700f5](https://github.com/DroneBridge/ESP32/assets/89179705/55621c42-8806-4996-afaa-616b666bc290)

![ae4bfa3e907206e0ce1694bb14448ca](https://github.com/DroneBridge/ESP32/assets/89179705/b8caac21-352d-4e85-a9e5-8cee4c5b9aef)

![829e67fc2d72abdee0dde552788e6d6](https://github.com/DroneBridge/ESP32/assets/89179705/2530c93c-c882-40aa-bec6-9bf45bf66c95)

![QQ浏览器截图20240311144525](https://github.com/DroneBridge/ESP32/assets/89179705/54bac244-f866-4d88-9adc-048dfecd114a)

**Comment by seeul8er** [comment]
Try switching them up: TX = 2 & RX = 3.
The the web interface must show UART data being received. Otherwise QGroundControl will not be able to see anything.

**Comment by YangChen1234** [comment]
I just tried to change the order and still can't connect to the ground station. How can I check the data from the serial port? thank you.
However, I connected an esp32-c3 development board outside the flight control to connect to the ground station normally
![微信图片_20240311163759](https://github.com/DroneBridge/ESP32/assets/89179705/a598f931-0926-4ecf-9201-0ad12ca18b42)
![c152e3ed2dbcbd4af8b7c309036b690](https://github.com/DroneBridge/ESP32/assets/89179705/23827994-6557-4f04-b7d2-8201c2afbc84)

**Comment by YangChen1234** [comment]
Because I want to achieve the ESP32-C3 directly welded to the flight control board, without having to attach an external development board

**Comment by seeul8er** [comment]
What flight controller exactly are you using (is there more documentation)? 
Based on the schematic I cannot tell how the ESP32C3 is supposed to receive the telemetry from the flight controller chip.

**Comment by YangChen1234** [comment]
[F405V3BLE-20231113.pdf](https://github.com/DroneBridge/ESP32/files/14557066/F405V3BLE-20231113.pdf)
I used AOCODARC STM32F405V3 flight control
This is the schematic, which connects BT-RX of the ESP32-C3 to TX5(PC12) of the stm32 BT-TX to RX5 (PD2) of the stm32

**Comment by YangChen1234** [comment]
Could you please help me check and confirm what to fill in for UART RX Pin and UART TX Pin.Thank you very much.

**Comment by YangChen1234** [comment]
![QQ浏览器截图20240311184114](https://github.com/DroneBridge/ESP32/assets/89179705/e7b7b7f2-7dde-4b74-a337-e1f82146495f)
![QQ浏览器截图20240311184103](https://github.com/DroneBridge/ESP32/assets/89179705/c57f9aca-41c0-4d7e-8ccf-5bed5ac20203)

**Comment by seeul8er** [comment]
> [F405V3BLE-20231113.pdf](https://github.com/DroneBridge/ESP32/files/14557066/F405V3BLE-20231113.pdf) I used AOCODARC STM32F405V3 flight control This is the schematic, which connects BT-RX of the ESP32-C3 to TX5(PC12) of the stm32 BT-TX to RX5 (PD2) of the stm32

You are right according to the schematic your first configuration should be correct: RX=2 & TX=3.
If configured correctly the ESP32 should be able to receive data from the FC. This is indicated by a growing number displayed as "UART received bytes" in the top left corner of the web interface. If that number remains 0 the ESP32 is not receiving anything (and therefore is not forwarding anything to QGroundControl). This could mean the pins are not configured correctly or the FC is not sending any data because of his configuration.

So first things first: Is the "UART received bytes" indicator showing any data in the web interface?

**Comment by 4O6FPV** [comment]
I think there is something more going on here as my uart received bytes stops as soon as I try and connect via UDP. this is probably the same as my issue opened .

**Comment by lida2003** [comment]
> I think there is something more going on here as my uart received bytes stops as soon as I try and connect via UDP. this is probably the same as my issue opened .

Thanks for the info. Is there any links about the issue? as we are going to test the link below, which we think it's passthough tunnel.
 seiral tool  ---- serial adapter ---- udp ---- udp tool

**Comment by 4O6FPV** [comment]
> > I think there is something more going on here as my uart received bytes stops as soon as I try and connect via UDP. this is probably the same as my issue opened .
> 
> Thanks for the info. Is there any links about the issue? as we are going to test the link below, which we think it's passthough tunnel. seiral tool ---- serial adapter ---- udp ---- udp tool

Mine was my own fault having cts/rts pins swapped which you do not even have enabled. do you have a link to the board you have looks very close to the waveshare one I have?

**Comment by lida2003** [comment]
> do you have a link to the board you have looks very close to the waveshare one I have?

Do you mean our [AOCODARC F405 V3 board](https://www.aliexpress.us/item/3256806449708141.html?pdp_npi=4%40dis%21USD%21US%20%2430.45%21US%20%2430.45%21%21%21218.00%21218.00%21%40213d7a8f17102030107224943ece0f%2112000037887060766%21sh%21US%212672834312%21&spm=a2g0o.store_pc_allItems_or_groupList.new_all_items_2007616112496.1005006636022893&gatewayAdapt=glo2usa)? 

It's just on the market, and bf/inav supported, and [ardupilot](https://github.com/SnapDragonfly/ardupilot/releases/tag/Copter-4.4.4-AORC-2024.01.18) is good to go.

**Comment by 4O6FPV** [comment]
what esp32 are you using?

**Comment by YangChen1234** [comment]
Thank you for your help. I have replaced a flight controller that can connect to the ground station.UART RX Pin =2 & UART TX Pin =3，this is fine.
![微信图片_20240312094614](https://github.com/DroneBridge/ESP32/assets/89179705/9efbef29-863a-4be1-a000-febbec027ec8)

![微信图片_20240312094610](https://github.com/DroneBridge/ESP32/assets/89179705/d10e5948-8f22-4286-90a8-a929d569cef6)
