### ISSUE TITLE
Esp32-cam

### ISSUE THREAD

**Issue by adri94** [DroneBridge/ESP32#8]
Hello,

Will this work with an esp32-cam ?
Would be nice to develop some stream and recognition.
Plus there is an ipex connector on it. 

Thank you for this nice project,

**Comment by seeul8er** [comment]
Thank you,

the application should work just fine on the ESP32-Cam board.
This project does not have support for the camera. You would have to add it yourself. I am not planning on implementing it since the max. possible frame rate is too low to be usable and the only supported codec is MJPEG.

**Comment by JulesThuillier** [comment]
Hello,

What about that : https://github.com/jeanlemotan/esp32-cam-fpv ?
Framerate seems decent, and it uses WifiBroadcast too.

**Comment by seeul8er** [comment]
@JulesThuillier Impressive, still too many downsides with regards to range etc.. The camera remains bad and I do not see any advantages compared to a analog setup
