### ISSUE TITLE
Channel assignment on esp32 C3

### ISSUE THREAD

**Issue by sierrayankee18** [DroneBridge/ESP32#84]
Hi.
i am using esp32 with drone bridge v2.0 on ground side and esp32c3 on air side with v1.5 running.

The ground side is configured to Wifi access point and air side to client mode.
i am connecting 4 air modules to 1 ground module.
What should i set the channel on ground side and air side to have no interference?

**Comment by seeul8er** [comment]
They must be on the same channel as the ground station of course. 
If there is too much interference then you need a second ground station on a different channel (ideally far away from the other channel) and assign the some drones to that channel.
