### ISSUE TITLE
HTTP 502 Error

### ISSUE THREAD

**Issue by vinura** [DroneBridge/ESP32#9]
When I try to save the settings i get HTTP 02 Error. Then it becomes unresponsive for a while. Any ideas ?

**Comment by vinura** [comment]
Also when i try to use Qground it says refuse to connect

**Comment by seeul8er** [comment]
What browser are you using? Maybe try a different one. I am aware that there is an issue sometimes.

**Comment by vinura** [comment]
I was using chrome. I will try a different browser and give you an update.

**Comment by GeorgeFlorian** [comment]
This did not changed.
https://github.com/DroneBridge/ESP32/issues/18
